
FROM rabbitmq:3.6.9-management

ADD plugins/rabbitmq_message_timestamp-3.6.x-0b333722.ez /plugins/
ADD plugins/rabbitmq_routing_node_stamp-3.6.x-024f8f22.ez /plugins/
ADD plugins/rabbitmq_delayed_message_exchange-0.0.1.ez /plugins/
ADD plugins/rabbitmq_management_themes-3.6.x-730495f1.ez /plugins/
ADD plugins/rabbitmq_clusterer-1.0.3.ez /plugins/rabbitmq_clusterer-1.0.3.ez

