#!/usr/bin/env bash
#
# This script is used to connect to any aws issue in tajawal
#
##########
#Variable#
##########
HOME=/var/www
DEVOPS_HOME=$HOME/devops
HCN_HOME=$HOME/hcn-devops
FCN_HOME=$HOME/fcn-devops
DWH_HOME=$HOME/dwh-devops
DEV_HOME=$HOME/dev-devops

############
if [ "$1" == "setup" ]; then
cp -f $DEVOPS_HOME/scripts/ssh /usr/local/bin/connect
    # DevOps Project
elif [ "$1" == "devops" ]; then
    ip=$(grep $2 $DEVOPS_HOME/app/inventory/hosts.ini | awk -F " " '{print $1}')
    env=$(grep $2 $DEVOPS_HOME/app/inventory/hosts.ini | awk -F " " '{print $3}' | awk -F "=" '{print $2}')
    if [ "$env" == "dev" ]; then
        ssh -o  ProxyCommand="ssh -i $DEVOPS_HOME/_ssh/it-admin-key.pem -W %h:%p ubuntu@tun-api-dev-endpoint.tajawal.io" ubuntu@$ip
     elif [ "$env" == "live" ]; then
        ssh -o  ProxyCommand="ssh -i $DEVOPS_HOME/_ssh/it-admin-key.pem -W %h:%p ubuntu@tun-api-live-endpoint.tajawal.io" ubuntu@$ip
    fi
    # Dev  Project
elif [ "$1" == "dev" ]; then
    ip=$(grep $2 $DEV_HOME/app/inventory/hosts.ini | awk -F " " '{print $1}')
    env=$(grep $2 $DEV_HOME/app/inventory/hosts.ini | awk -F " " '{print $3}' | awk -F "=" '{print $2}')
    if [ "$env" == "dev" ]; then
        ssh -o  ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p ubuntu@tun-api-dev-endpoint.tajawal.io" ubuntu@$ip
     elif [ "$env" == "live" ]; then
        ssh -o  ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p ubuntu@tun-api-live-endpoint.tajawal.io" ubuntu@$ip
    fi
    # DataWare House Connect Project
elif [ "$1" == "dwh" ]; then
    ip=$(grep $2 $DWH_HOME/app/inventory/hosts.ini | awk -F " " '{print $1}')
    env=$(grep $2 $DWH_HOME/app/inventory/hosts.ini | awk -F " " '{print $3}' | awk -F "=" '{print $2}')
    if [ "$env" == "dev" ]; then
        ssh -o  ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p ubuntu@34.245.252.247" ubuntu@$ip
     elif [ "$env" == "live" ]; then
        ssh -o  ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p ubuntu@34.247.94.143" ubuntu@$ip
    fi
    # Ambari Project
elif [ "$1" == "amrabi" ]; then
    ip=$(grep $2 $DEVOPS_HOME/app/inventory/hosts.ini | awk -F " " '{print $1}')
    env=$(grep $2 $DEVOPS_HOME/app/inventory/hosts.ini | awk -F " " '{print $3}' | awk -F "=" '{print $2}')
    if [ "$env" == "dev" ]; then
        ssh -o  ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p centos@tun-api-dev-endpoint.tajawal.io" centos@$ip
    fi
    # Flight Connect Project
elif [ "$1" == "fcn" ]; then
    ip=$(grep $2 $FCN_HOME/app/inventory/hosts.ini | awk -F " " '{print $1}')
    env=$(grep $2 $FCN_HOME/app/inventory/hosts.ini | awk -F " " '{print $3}' | awk -F "=" '{print $2}')
    if [ "$env" == "dev" ]; then
        ssh -o  ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p ubuntu@34.246.15.102" ubuntu@$ip
    fi
    # Hotel Connect Project
elif [ "$1" == "hcn" ]; then
    ip=$(grep $2 $HCN_HOME/app/inventory/hosts.ini | awk -F " " '{print $1}')
    env=$(grep $2 $HCN_HOME/app/inventory/hosts.ini | awk -F " " '{print $3}' | awk -F "=" '{print $2}')
    if [ "$env" == "dev" ]; then
        ssh -o  ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p ubuntu@34.242.191.123" ubuntu@$ip
    fi
else
echo  -e  "Usage: <command> <env> <EcName> \n   eg. connect devops mongo_cluster_oms-prod-0-a "
fi
